# Generated by Django 4.0 on 2023-02-09 06:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=30)),
                ('room_subject', models.CharField(max_length=100)),
                ('room_boss', models.CharField(max_length=100)),
                ('limit_people', models.IntegerField(validators=[django.core.validators.MinLengthValidator(2), django.core.validators.MaxLengthValidator(20)])),
                ('limit_date', models.IntegerField(validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(10)])),
            ],
        ),
    ]
