# Generated by Django 4.0 on 2023-02-03 05:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=30)),
                ('room_suject', models.CharField(max_length=100)),
                ('limit_people', models.IntegerField(help_text='최대 인원 수를 설정하세요(20인 이하)', validators=[django.core.validators.MinLengthValidator(2), django.core.validators.MaxLengthValidator(20)])),
                ('limit_date', models.IntegerField(help_text='설정 일수 후 방이 삭제 됩니다.', validators=[django.core.validators.MinLengthValidator(2), django.core.validators.MaxLengthValidator(10)])),
            ],
        ),
    ]
