# Generated by Django 4.1.6 on 2023-02-20 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("review_content", models.CharField(max_length=2000)),
                ("review_creater", models.CharField(max_length=100)),
                ("review_date", models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("room_title", models.CharField(max_length=30)),
                ("room_content", models.CharField(max_length=2000)),
                ("room_image", models.ImageField(blank=True, null=True, upload_to="")),
                ("room_creater", models.CharField(max_length=100)),
                ("room_date", models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
