# Generated by Django 4.1.6 on 2023-02-20 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="room_image",
            field=models.ImageField(blank=True, null=True, upload_to="%Y/%m/%d"),
        ),
    ]
