# Generated by Django 4.1.6 on 2023-02-22 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='room_image',
        ),
        migrations.AddField(
            model_name='room',
            name='room_image1',
            field=models.ImageField(null=True, upload_to='media/2023/02/22/'),
        ),
        migrations.AddField(
            model_name='room',
            name='room_image2',
            field=models.ImageField(null=True, upload_to='media/2023/02/22/'),
        ),
        migrations.AddField(
            model_name='room',
            name='room_image3',
            field=models.ImageField(null=True, upload_to='media/2023/02/22/'),
        ),
    ]
