# Generated by Django 4.0 on 2023-02-03 07:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='room_suject',
            new_name='room_subject',
        ),
        migrations.AlterField(
            model_name='room',
            name='limit_date',
            field=models.IntegerField(validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(10)]),
        ),
        migrations.AlterField(
            model_name='room',
            name='limit_people',
            field=models.IntegerField(validators=[django.core.validators.MinLengthValidator(2), django.core.validators.MaxLengthValidator(20)]),
        ),
    ]
