# Generated by Django 4.0 on 2023-02-12 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_boss',
            field=models.CharField(default='', max_length=100),
        ),
    ]
