# Generated by Django 4.0 on 2023-02-06 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0002_rename_room_suject_room_room_subject_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(max_length=10)),
                ('chat_pw', models.CharField(max_length=20)),
                ('chat_email', models.EmailField(max_length=254)),
                ('chat_info', models.CharField(max_length=1000)),
            ],
        ),
    ]
