# Generated by Django 4.1.6 on 2023-02-22 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0003_rename_room_image1_room_room_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='room_image',
            new_name='room_image1',
        ),
        migrations.AddField(
            model_name='room',
            name='room_image2',
            field=models.ImageField(null=True, upload_to='media/2023/02/22/'),
        ),
        migrations.AddField(
            model_name='room',
            name='room_image3',
            field=models.ImageField(null=True, upload_to='media/2023/02/22/'),
        ),
    ]
