# Generated by Django 4.1.6 on 2023-02-24 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0004_rename_room_image_room_room_image1_room_room_image2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_room', models.IntegerField()),
                ('review_id', models.IntegerField()),
                ('review_content', models.CharField(max_length=2000)),
                ('review_creater', models.CharField(max_length=100)),
                ('review_date', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='room',
            name='room_image1',
            field=models.ImageField(null=True, upload_to='media/2023/02/24/'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_image2',
            field=models.ImageField(null=True, upload_to='media/2023/02/24/'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_image3',
            field=models.ImageField(null=True, upload_to='media/2023/02/24/'),
        ),
    ]
