# Generated by Django 4.0 on 2023-02-09 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0004_alter_account_chat_info'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
