# Generated by Django 3.2.16 on 2023-04-12 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0005_rereview_alter_room_room_image1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_image1',
            field=models.ImageField(null=True, upload_to='media/2023/04/12/'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_image2',
            field=models.ImageField(null=True, upload_to='media/2023/04/12/'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_image3',
            field=models.ImageField(null=True, upload_to='media/2023/04/12/'),
        ),
    ]
